layout_spectrum: 0.08281026
typography_spectrum: 0.9617184
color:
  saturation: 0.7995605
  lightness: 0.7826204
  brandStrength: 0.1881305
  rhythmicContrast: 0.9771423
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Canon.rocks
